### ISSUE TITLE
Different name for multiple composed mutations?

### ISSUE THREAD

**Issue by thealjey** [lhz516/with-mutation-state#1]
I want each of my `compose`d mutations to have a different name.

```js
mutationState({name: "mutation"})(compose(
  graphql(...),
  graphql(...),
  graphql(...),
)(MyComponent));
```

Maybe the "name" option could be a function that resolves to a string?
Or, better yet, use the name configured in each `graphql(..., {name: 'myMutation2'})`.

**Comment by lhz516** [comment]
@thealjey This HOC currently only supports a single `mutation` object.

You can try this:
```js
mutationState({ name: 'mutation1' })(
  mutationState({ name: 'mutation2' })(
    mutationState({ name: 'mutation3' })(
      compose(
        graphql(...),
        graphql(...),
        graphql(...),
      )(MyComponent),
    ),
  ),
)
```
