### ISSUE TITLE
Error: Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by rahulbhankar786** [lhz516/with-mutation-state#2]
Error: Couldn't find preset "es2015" relative to directory "C:\\Users\\rahul\\Desktop\\Projects\\ordital-react-native\\node_modules\\react-apollo-mutation-state"

**Comment by lhz516** [comment]
I don't think it's an issue related to this package. If you install `react-apollo-mutation-state` via `npm`, you should get the compiled/minified code in `lib` directory which is in pure es5.
